DBX_HOSTNAME = "adb-7816564244592825.5.azuredatabricks.net"
DBX_HTTP_PATH = "/sql/1.0/warehouses/8e1e77a640c2b38d"
DBX_CATALOG = "usr1_dw"
DBX_PROJECT_SCHEMA = "project_silver"
DBX_ASSET_SCHEMA = "kobo_silver"


DBX_ACCESS_TOKEN = "EoEjZsOl8W6Iv-iax_8O-GlOUxTauRaiSjOQTlrzOyJteBMRVfQe-IQknu5kN0VQ"